imageKey:
    repository: fortresscomputingcontosoair.azurecr.io/fortresscomputingcontosoair
    pullPolicy: IfNotPresent
    tag: latest
service:
    annotations: {}
    type: LoadBalancer
    port: "80"
